version: "3.7"

services:
    flaskdocker:
        container_name: flask-docker
        build:
            context: .
            dockerfile: './Dockerfile'
        ports: 
            - "5000:5000"
        volumes:
            - './:/app'